export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const EDIT_USER = 'EDIT_USER'
export const USER_EDITED = 'USER_EDITED'
export const CANCEL_EDIT = 'CANCEL_EDIT'
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER'
